namespace SmartHunter.Game.Config
{
    public class PlayerDataConfig
    {
        static class StatusEffectTags
        {
            public static string[] Buff           = { "Buff" };
            public static string[] Debuff         = { "Debuff" };
            public static string[] HuntingHorn    = { "HuntingHorn", "Buff" };
            public static string[] CoralOrchestra = { "CoralOrchestra", "Buff" };
            public static string[] Equipment      = { "Equipment", "Buff" };
            public static string[] Weapon         = { "Weapon", "Buff" };
        }

        public StatusEffectConfig[] StatusEffects =
        {
            new StatusEffectConfig("LOC_STATUS_EFFECT_SELF_IMPROVEMENT",                     StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "38"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ATTACK_UP_S",                          StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "3C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ATTACK_UP_L",                          StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "40"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_HEALTH_BOOST_S",                       StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "44"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_HEALTH_BOOST_L",                       StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "48"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_STAMINA_USE_REDUCED_S",                StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "4C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_STAMINA_USE_REDUCED_L",                StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "50"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_WIND_PRESSURE_NEGATED",                StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "54"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ALL_WIND_PRESSURE_NEGATED",            StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "58"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DEFENSE_UP_S",                         StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "5C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DEFENSE_UP_L",                         StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "60"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_TOOL_USE_DRAIN_REDUCED_S",             StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "64"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_TOOL_USE_DRAIN_REDUCED_L",             StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "68"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_HEALTH_RECOVERY_S",                    StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "80"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_HEALTH_RECOVERY_L",                    StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "84"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_EARPLUGS_S",                           StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "88"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_EARPLUGS_L",                           StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "8C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DIVINE_PROTECTION",                    StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "90"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_SCOUTFLY_POWER_UP",                    StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "94"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ENVIRONMENTAL_DAMAGE_NEGATED",         StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "98"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_STUN_NEGATED",                         StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "9C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_PARALYSIS_NEGATED",                    StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "A0"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_TREMORS_NEGATED",                      StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "A4"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_MUCK_RESISTANCE",                      StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "A8"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_FIRE_RESISTANCE_BOOST_S",              StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "AC"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_FIRE_RESISTANCE_BOOST_L",              StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "B0"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_WATER_RESISTANCE_BOOST_S",             StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "B4"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_WATER_RESISTANCE_BOOST_L",             StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "B8"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_THUNDER_RESISTANCE_BOOST_S",           StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "BC"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_THUNDER_RESISTANCE_BOOST_L",           StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "C0"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ICE_RESISTANCE_BOOST_S",               StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "C4"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ICE_RESISTANCE_BOOST_L",               StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "C8"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DRAGON_RESISTANCE_BOOST_S",            StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "CC"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DRAGON_RESISTANCE_BOOST_L",            StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "D0"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ELEMENTAL_ATTACK_BOOST",               StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "D4"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_BLIGHT_NEGATED",                       StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "D8"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_KNOCKBACKS_NEGATED",                   StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "E4"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ELEMENTAL_RESISTANCE_UP",              StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "EC"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_AFFINITY_UP",                          StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "F0"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ALL_AILMENTS_NEGATED",                 StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "F4"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_WIND_PRESSURE_NEGATED_AND_EARPLUGS_S", StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "F8"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ABNORMAL_STATUS_ATTACK_INCREASED",     StatusEffectTags.HuntingHorn,    StatusEffectConfig.MemorySource.Base,      "FC"),
                                                                                                                                                                         
            new StatusEffectConfig("LOC_STATUS_EFFECT_ATTACK_UP_S",                          StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "104"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ATTACK_UP_L",                          StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "108"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DEFENSE_UP_S",                         StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "10C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DEFENSE_UP_L",                         StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "110"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_AFFINITY_UP",                          StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "114"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_HEALTH_RECOVERY",                      StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "118"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_HEALTH_BOOST",                         StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "11C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_STAMINA_USE_REDUCED",                  StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "120"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DIVINE_PROTECTION",                    StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "128"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_STUN_NEGATED",                         StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "130"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_PARALYSIS_NEGATED",                    StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "134"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_TREMORS_NEGATED",                      StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "138"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_EARPLUGS_S",                           StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "13C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_WIND_PRESSURE_NEGATED",                StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "140"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ENVIRONMENTAL_DAMAGE_NEGATED",         StatusEffectTags.CoralOrchestra, StatusEffectConfig.MemorySource.Base,      "144"),
                                                                                                                                                                         
            new StatusEffectConfig("LOC_STATUS_EFFECT_POISON",                               StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "554"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_FIREBLIGHT",                           StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "55C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_THUNDERBLIGHT",                        StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "560"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_WATERBLIGHT",                          StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "564"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ICEBLIGHT",                            StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "568"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DRAGONBLIGHT",                         StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "56C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_BLEEDING",                             StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "570"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_BLEEDING_RECOVERY",                    StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "574"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_EFFLUVIA",                             StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "578"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DEFENSE_DOWN",                         StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "57C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ELEMENTAL_RESISTANCE_DOWN",            StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "584"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_NO_ITEMS",                             StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "58C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_BLASTBLIGHT",                          StatusEffectTags.Debuff,         StatusEffectConfig.MemorySource.Base,      "590"),
                                                                                                                                                                         
            new StatusEffectConfig("LOC_STATUS_EFFECT_DASH_JUICE",                           StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "5B8"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_WIGGLY_LITCHI",                        StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "5BC"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_IMMUNIZER",                            StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "5C0"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_MIGHT_PILL",                           StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "5C8",  new MemoryConditionConfig((byte)1, "5D0")),
            new StatusEffectConfig("LOC_STATUS_EFFECT_MIGHT_SEED",                           StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "5C8",  new MemoryConditionConfig((byte)0, "5D0")),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ADAMANT_PILL",                         StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "5D8",  new MemoryConditionConfig((byte)1, "5E4")),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ADAMANT_SEED",                         StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "5D8",  new MemoryConditionConfig((byte)0, "5E4")),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DEMON_POWDER",                         StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "5EC"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_HARDSHELL_POWDER",                     StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "5F0"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_DEMONDRUG",                            StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      null,   new MemoryConditionConfig(1, "5FC")),
            new StatusEffectConfig("LOC_STATUS_EFFECT_MEGA_DEMONDRUG",                       StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      null,   new MemoryConditionConfig(2, "5FC")),
            new StatusEffectConfig("LOC_STATUS_EFFECT_ARMORSKIN",                            StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      null,   new MemoryConditionConfig(1, "600")),
            new StatusEffectConfig("LOC_STATUS_EFFECT_MEGA_ARMORSKIN",                       StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      null,   new MemoryConditionConfig(2, "600")),
            new StatusEffectConfig("LOC_STATUS_EFFECT_COOL_DRINK",                           StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "60C"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_PROTECTIVE_POLISH",                    StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "644"),
            new StatusEffectConfig("LOC_STATUS_EFFECT_AFFINITY_SLIDING",                     StatusEffectTags.Buff,           StatusEffectConfig.MemorySource.Base,      "648"),

            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_GHILLIE",                           StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "A8C"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_TEMPORAL",                          StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "A90"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_ROCKSTEADY",                        StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "A98"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_CHALLENGER",                        StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "A9C"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_VITALITY",                          StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AA0"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_FIREPROOF",                         StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AA4"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_WATERPROOF",                        StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AA8"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_ICEPROOF",                          StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AAC"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_THUNDERPROOF",                      StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AB0"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_DRAGONPROOF",                       StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AB4"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_GLIDER",                            StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "ABC"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_EVASION",                           StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AC0"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_IMPACT",                            StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AC4"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_APOTHECARY",                        StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AC8"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_IMMUNITY",                          StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "ACC"),
            new StatusEffectConfig("LOC_EQUIPMENT_MANTLE_BANDIT",                            StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AD4"),
            new StatusEffectConfig("LOC_EQUIPMENT_ASSASSINS_HOOD",                           StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "AD8"),
            new StatusEffectConfig("LOC_EQUIPMENT_AFFINITY_BOOSTER",                         StatusEffectTags.Equipment,      StatusEffectConfig.MemorySource.Equipment, "B68"),

            new StatusEffectConfig("LOC_WEAPON_INSECT_GLAIVE_ATTACK",                        StatusEffectTags.Weapon,         StatusEffectConfig.MemorySource.Weapon,    "1FE8", new MemoryConditionConfig(".*rod[0-9]", "290", "3E0", "10")),
            new StatusEffectConfig("LOC_WEAPON_INSECT_GLAIVE_SPEED",                         StatusEffectTags.Weapon,         StatusEffectConfig.MemorySource.Weapon,    "1FEC", new MemoryConditionConfig(".*rod[0-9]", "290", "3E0", "10")),
            new StatusEffectConfig("LOC_WEAPON_INSECT_GLAIVE_DEFENSE",                       StatusEffectTags.Weapon,         StatusEffectConfig.MemorySource.Weapon,    "1FF0", new MemoryConditionConfig(".*rod[0-9]", "290", "3E0", "10")),
            new StatusEffectConfig("LOC_WEAPON_LONGSWORD_SPIRIT_GAUGE_REGEN",                StatusEffectTags.Weapon,         StatusEffectConfig.MemorySource.Weapon,    "1FF8", new MemoryConditionConfig(".*swo[0-9]", "290", "3E0", "10")),
            new StatusEffectConfig("LOC_WEAPON_LONGSWORD_STEADY_SPIRIT_LEVEL",               StatusEffectTags.Weapon,         StatusEffectConfig.MemorySource.Weapon,    "2008", new MemoryConditionConfig(".*swo[0-9]", "290", "3E0", "10")),
            new StatusEffectConfig("LOC_WEAPON_CHARGE_BLADE_SHIELD_CHARGE",                  StatusEffectTags.Weapon,         StatusEffectConfig.MemorySource.Weapon,    "1FF8", new MemoryConditionConfig(".*caxe[0-9]", "290", "3E0", "10")),
            new StatusEffectConfig("LOC_WEAPON_CHARGE_BLADE_BLADE_CHARGE",                   StatusEffectTags.Weapon,         StatusEffectConfig.MemorySource.Weapon,    "1FFC", new MemoryConditionConfig(".*caxe[0-9]", "290", "3E0", "10")),
            new StatusEffectConfig("LOC_WEAPON_SWITCH_AXE_AMPED_STATE",                      StatusEffectTags.Weapon,         StatusEffectConfig.MemorySource.Weapon,    "1FD4", new MemoryConditionConfig(".*saxe[0-9]", "290", "3E0", "10")),
            new StatusEffectConfig("LOC_WEAPON_HAMMER_POWER_CHARGE",                         StatusEffectTags.Weapon,         StatusEffectConfig.MemorySource.Weapon,    null,   new MemoryConditionConfig((byte)1, "1FC4"), new MemoryConditionConfig(".*ham[0-9]", "290", "3E0", "10"))
        };
    }
}