namespace SmartHunter.Game.Config
{
    public class PlayerDataConfig
    {
        public PlayerStatusEffectConfig[] PlayerStatusEffects =
        {
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_SELF_IMPROVEMENT", "38"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ATTACK_UP_S", "3C"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ATTACK_UP_L", "40"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_HEALTH_BOOST_S", "44"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_HEALTH_BOOST_L", "48"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_STAMINA_USE_REDUCED_S", "4C"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_STAMINA_USE_REDUCED_L", "50"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_WIND_PRESSURE_NEGATED", "54"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ALL_WIND_PRESSURE_NEGATED", "58"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_DEFENSE_UP_S", "5C"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_DEFENSE_UP_L", "60"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_TOOL_USE_DRAIN_REDUCED_S", "64"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_TOOL_USE_DRAIN_REDUCED_L", "68"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_HEALTH_RECOVERY_S", "80"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_HEALTH_RECOVERY_L", "84"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_EARPLUGS_S", "88"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_EARPLUGS_L", "8C"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_DIVINE_PROTECTION", "90"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_SCOUTFLY_POWER_UP", "94"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ENVIRONMENTAL_DAMAGE_NEGATED", "98"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_STUN_NEGATED", "9C"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_PARALYSIS_NEGATED", "A0"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_TREMORS_NEGATED", "A4"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_MUCK_RESISTANCE", "A8"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_FIRE_RESISTANCE_BOOST_S", "AC"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_FIRE_RESISTANCE_BOOST_L", "B0"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_WATER_RESISTANCE_BOOST_S", "B4"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_WATER_RESISTANCE_BOOST_L", "B8"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_THUNDER_RESISTANCE_BOOST_S", "BC"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_THUNDER_RESISTANCE_BOOST_L", "C0"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ICE_RESISTANCE_BOOST_S", "C4"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ICE_RESISTANCE_BOOST_L", "C8"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_DRAGON_RESISTANCE_BOOST_S", "CC"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_DRAGON_RESISTANCE_BOOST_L", "D0"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ELEMENTAL_ATTACK_BOOST", "D4"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_BLIGHT_NEGATED", "D8"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_KNOCKBACKS_NEGATED", "E4"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ELEMENTAL_RESISTANCE_UP", "EC"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_AFFINITY_UP", "F0"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ALL_AILMENTS_NEGATED", "F4"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_WIND_PRESSURE_NEGATED_AND_EARPLUGS_S", "F8"),
            new PlayerStatusEffectConfig("Horn", "LOC_STATUS_EFFECT_ABNORMAL_STATUS_ATTACK_INCREASED", "FC"),

            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_ATTACK_UP_S", "104"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_ATTACK_UP_L", "108"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_DEFENSE_UP_S", "10C"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_DEFENSE_UP_L", "110"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_AFFINITY_UP", "114"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_HEALTH_RECOVERY", "118"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_HEALTH_BOOST", "11C"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_STAMINA_USE_REDUCED", "120"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_DIVINE_PROTECTION", "128"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_STUN_NEGATED", "130"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_PARALYSIS_NEGATED", "134"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_TREMORS_NEGATED", "138"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_EARPLUGS_S", "13C"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_WIND_PRESSURE_NEGATED", "140"),
            new PlayerStatusEffectConfig("Coral", "LOC_STATUS_EFFECT_ENVIRONMENTAL_DAMAGE_NEGATED", "144"),

            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_POISON", "554"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_FIREBLIGHT", "55C"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_THUNDERBLIGHT", "560"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_WATERBLIGHT", "564"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_ICEBLIGHT", "568"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_DRAGONBLIGHT", "56C"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_BLEEDING", "570"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_BLEEDING_RECOVERY", "574"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_EFFLUVIA", "578"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_DEFENSE_DOWN", "57C"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_ELEMENTAL_RESISTANCE_DOWN", "584"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_NO_ITEMS", "58C"),
            new PlayerStatusEffectConfig("Debuff", "LOC_STATUS_EFFECT_BLASTBLIGHT", "590"),

            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_DASH_JUICE", "5B8"),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_WIGGLY_LITCHI", "5BC"),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_IMMUNIZER", "5C0"),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_MIGHT_PILL", "5C8", new PlayerStatusEffectConditionConfig("5D0", 1)),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_MIGHT_SEED", "5C8", new PlayerStatusEffectConditionConfig("5D0", 0)),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_ADAMANT_PILL", "5D8", new PlayerStatusEffectConditionConfig("5E4", 1)),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_ADAMANT_SEED", "5D8", new PlayerStatusEffectConditionConfig("5E4", 0)),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_DEMON_POWDER", "5EC"),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_HARDSHELL_POWDER", "5F0"),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_DEMONDRUG", null, new PlayerStatusEffectConditionConfig("5FC", 1)),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_MEGA_DEMONDRUG", null, new PlayerStatusEffectConditionConfig("5FC", 2)),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_ARMORSKIN", null, new PlayerStatusEffectConditionConfig("600", 1)),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_MEGA_ARMORSKIN", null, new PlayerStatusEffectConditionConfig("600", 2)),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_COOL_DRINK", "60C"),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_PROTECTIVE_POLISH", "644"),
            new PlayerStatusEffectConfig("Buff", "LOC_STATUS_EFFECT_AFFINITY_SLIDING", "648"),

            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_GHILLIE", "A5C", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_TEMPORAL", "A60", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_ROCKSTEADY", "A68", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_CHALLENGER", "A6C", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_VITALITY", "A70", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_FIREPROOF", "A74", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_WATERPROOF", "A78", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_ICEPROOF", "A7C", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_THUNDERPROOF", "A80", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_DRAGONPROOF", "A84", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_GLIDER", "A8C", null, PlayerStatusEffectConfig.MemorySource.Equipment),

            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_EVASION", "A90", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_IMPACT", "A94", null, PlayerStatusEffectConfig.MemorySource.Equipment),

            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_APOTHECARY", "A98", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_IMMUNITY", "A9C", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_MANTLE_BANDIT", "AA4", null, PlayerStatusEffectConfig.MemorySource.Equipment),
            new PlayerStatusEffectConfig("Equipment", "LOC_EQUIPMENT_AFFINITY_BOOSTER", "B38", null, PlayerStatusEffectConfig.MemorySource.Equipment)
        };
    }
}